### ISSUE TITLE
H6159 wrong brightness, showing at 40% after api state, physical light is 100%

### ISSUE THREAD

**Issue by LaggAt** [LaggAt/home-assistant-core#2]
https://community.home-assistant.io/t/govee-led-strips-integration/228516/59?u=laggat 

So when I did this capture, I had just slid the brightness slider all the way up. Light was at 100% brightness in the room. After HA received the status from the API, the slider moved back to the position shown in the screenshot.

In other words every time I slide the slider all the way up, after around 10 seconds it will jump back down to the 40% or so mark. The conversion back doesn’t seem to be happening.

**Comment by Scope666** [comment]
At some point I can do a longer debug log capture to try and provide more info on the subject.

**Comment by Scope666** [comment]
Here's a quick video demonstration of the behavior:

https://www.screencast.com/t/xNWGMGag

**Comment by LaggAt** [comment]
Feature idea
https://community.home-assistant.io/t/govee-led-strips-integration/228516/66?u=laggat

**Comment by LaggAt** [comment]
simple learning feature described here:
https://community.home-assistant.io/t/govee-led-strips-integration/228516/76?u=laggat

working on it in these feature branches:
library: feature/learn_brightness
ha-core: feature/govee_learn_brightness

**Comment by Scope666** [comment]
If you need me to do any tests, just let me know.  I can turn on debug and capture logs, or anything else you need.

**Comment by LaggAt** [comment]
solved and released in new zip.
